language: node_js
node_js: 16
dist: jammy
cache:
  npm: false
branches:
  only:
    - master
env:
  global:
    # GH_TOKEN (cozy-bot)
    - secure: "kZSPdYXbbwI3fgnZ4G9GQncQJM+PXOmF2iTeRMYLgNqWOoUC8vu3LglmecmY7IM5nMr7RY2H4QYQUas8ZQvpY8s82Rr5CvxasEfgLb4xPy2VRyYAR+yVsX38nitJTpciwqwdaY3Z3mIh/RzChHfyQ9GS4hI6GdTxlxWUgQdmRbzsw02qDFPCfwhZxn0Bi+wM6b9k9bbxhKyk2eSxeizwQSFjLh4M7gxi5K+3eRV6yKBLQAiqkPat0ekPX19olnxP8NnzeeAaX57EBUaywuyzadmSJlfHgKM02CgVacpNP+6RSAM+bjMd0Ua3hmMaVgxXwEhirpq2oSIATa0chyO5yulMC5P7hJl/F7Kt5YXWt4ikWAs6N1hiTYaXkaDuYE4hJ1Bg3dO4yL5njSC2/1ytwM9f+C4i4GCPsbrBH3QKT5P53CNA52CtTujcwsn6bS5NlBskWwXk5Ey5HFLo+w5LEEbDP91D3ylEkDWF0Yf8XqzwapiW+jUiceeCbEZMboe3laMinM/t/atgszCUgGCyD702aFUmwJuQHzu/NNryazlqbOnknlWolXsS/K9EWWF9eL8e/jBJLfMlpOEGlZP5mbbjwoeDEdaHWhNubQIqdgiJCozp1NQaagHK2Rw3cF2z9+ev/qGhHvwJXZd5xcsn/He6kHlszDFqaAccZgBFmKU="
script:
  - yarn lint
  - yarn test
  - yarn build
before_deploy:
  - touch .npmignore
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run semantic-release
  on:
    branch: master
    repo: cozy/cozy-bar
