settings:
  -
    - label: storage
      storage: true
      disabled_link: true
      currentDiskUsage: null
  -
    - label: help
      external: true
      href: https://docs.cozy.io/
    - label: email
      href: mailto:contact@cozycloud.cc
  -
    - label: logout
      href: /logout
apps: false
