settings:
  -
    - label: help
      external: true
      href: https://docs.cozy.io/
    - label: email
      href: mailto:contact@cozycloud.cc
  -
    - label: logout
      href: /logout
apps: false
